

read_hdl -sv {
./rtl/ip/axi2apb_bridge/axi_typedef_pkg.sv 
}


read_hdl {
./rtl/common/axi_master_wrapper/axi_wrapper_top.v
./rtl/common/axi_master_wrapper/axi_rw_engine.v
./rtl/common/axi_slave_with_data_memory/axi_4lite_slave.v  
./rtl/common/axi_slave_with_data_memory/axi_datamem_wrapper.v  
./rtl/common/mem/data_memory.v
./rtl/common/axi_slave_with_instruction_memory/axi_instmem_wrapper.v
./rtl/common/mem/instruction_memory.v 
./rtl/common/soc_mmr_apb_wrapper.v
./rtl/ip/basic_isa/rv32i_core.v 
./rtl/ip/basic_isa/pc_reg.v
./rtl/ip/basic_isa/if_stage_simple_btb.v
./rtl/ip/basic_isa/dynamic_branch_predictor.v
./rtl/ip/basic_isa/btb_file.v
./rtl/ip/basic_isa/btb_read.v
./rtl/ip/basic_isa/btb_write.v
./rtl/ip/basic_isa/btb.v
./rtl/ip/basic_isa/register_file.v
./rtl/ip/basic_isa/control_unit.v
./rtl/ip/basic_isa/top_decode.v
./rtl/ip/basic_isa/decode_unit.v
./rtl/ip/basic_isa/arithmetic_unit32.v
./rtl/ip/basic_isa/logical_unit32.v
./rtl/ip/basic_isa/shift_unit32.v
./rtl/ip/basic_isa/compare_unit32.v
./rtl/ip/basic_isa/branch_jump_unit.v
./rtl/ip/basic_isa/alu_top32.v
./rtl/ip/basic_isa/forwarding_unit.v
./rtl/ip/basic_isa/execute_stage.v
./rtl/ip/basic_isa/ex_mem_pipe.v
./rtl/ip/basic_isa/load_datapath.v
./rtl/ip/basic_isa/store_datapath.v
./rtl/ip/basic_isa/data_mem_top.v
./rtl/ip/basic_isa/mem_stage.v
./rtl/ip/basic_isa/mem_wb_pipe.v
./rtl/ip/basic_isa/wb_stage.v
./rtl/ip/basic_isa/if_id_pipe.v
./rtl/ip/basic_isa/id_ex_pipe.v
./rtl/ip/basic_isa/hazard_unit.v
./rtl/ip/basic_isa/halt_fsm.v
./rtl/ip/basic_isa/int_ctrl_logic.v
./rtl/ip/basic_isa/trace_core.v
./rtl/ip/csr/soc_csr_top.v
./rtl/ip/csr/soc_csr_read_mux.v      
./rtl/ip/csr/soc_csr_reg_file.v
./rtl/ip/csr/satp_csr.v
./rtl/ip/csr/mintstatus_csr.v
./rtl/ip/csr/misa_csr.v
./rtl/ip/csr/mtvec_csr.v
./rtl/ip/csr/mepc_csr.v
./rtl/ip/csr/mie_csr.v
./rtl/ip/csr/mtval_csr.v
./rtl/ip/csr/mcause_csr.v
./rtl/ip/csr/mscratch_csr.v
./rtl/ip/csr/mstatus_csr.v
./rtl/ip/csr/marchid_csr.v
./rtl/ip/csr/mhartid_csr.v
./rtl/ip/csr/mimpid_csr.v
./rtl/ip/csr/mvendorid_csr.v
./rtl/ip/csr/dcsr.v
./rtl/ip/csr/dpc_csr.v
./rtl/ip/debug_module/DM_ace.v               
./rtl/ip/debug_module/dmi_transaction_fsm.v  
./rtl/ip/debug_module/DTM_cdc.v              
./rtl/ip/debug_module/jtag_tap_controller.v   
./rtl/ip/debug_module/dmi_address_decoder.v  
./rtl/ip/debug_module/dm_program_buffer.v    
./rtl/ip/debug_module/dtmcs_register.v             
./rtl/ip/debug_module/jtag_tdo_mux.v         
./rtl/ip/debug_module/dmi_data_register.v    
./rtl/ip/debug_module/DM_reg.v               
./rtl/ip/debug_module/sba_address_decoder.v     
./rtl/ip/debug_module/dmi_request.v                
./rtl/ip/debug_module/jtag_idcode_dr.v       
./rtl/ip/debug_module/dmi_response_buffer.v  
./rtl/ip/debug_module/DTM_bypass.v           
./rtl/ip/debug_module/jtag_ir.v              
./rtl/ip/debug_module/sba_control_fsm.v
./rtl/ip/debug_module/trace_debug.v
./rtl/ip/debug_module/debug_module.v
./rtl/ip/int_ctrl/soc_ic_top.v             
./rtl/ip/int_ctrl/soc_int_rec.v            
./rtl/ip/int_ctrl/soc_mmr_ctrl.v           
./rtl/ip/int_ctrl/soc_mmr_reg_file.v       
./rtl/ip/int_ctrl/soc_priority_resolve.v 
./rtl/ip/int_ctrl/soc_interrupt_control.v  
./rtl/ip/int_ctrl/soc_irg.v                
./rtl/ip/int_ctrl/soc_mmr_op_mux.v         
./rtl/ip/int_ctrl/soc_mmr_top.v
./rtl/common/pte_memory_wrapper/pte_controller.v  
./rtl/common/mem/pte_memory.v
./rtl/common/pte_memory_wrapper/pte_wrapper.v
./rtl/ip/TRACE_UNIT/inst_trace_enformat2.v              
./rtl/ip/TRACE_UNIT/inst_trace_enformat3_sf1.v  
./rtl/ip/TRACE_UNIT/inst_trace_enformat3_enableblock.v  
./rtl/ip/TRACE_UNIT/inst_trace_enformat3_sf2.v  
./rtl/ip/TRACE_UNIT/branch_map.v                 
./rtl/ip/TRACE_UNIT/inst_trace_enformat3_mux.v          
./rtl/ip/TRACE_UNIT/inst_trace_enformat3_sf3.v  
./rtl/ip/TRACE_UNIT/inst_trace_enformat1.v       
./rtl/ip/TRACE_UNIT/inst_trace_enformat3_sf0.v          
./rtl/ip/TRACE_UNIT/inst_trace_enmodule.v
./rtl/common/apb_slave_psel_wrapper.v

}

read_hdl -sv {
./rtl/ip/axi2apb_bridge/axi_typedef_pkg.sv   
./rtl/ip/mmu/arbiter_mmu.sv              
./rtl/ip/mmu/l2tlb.sv                
./rtl/ip/mmu/prefetcher.sv           
./rtl/ip/mmu/replace_1_port_itlb.sv  
./rtl/ip/mmu/tlb_ctrl.sv 
./rtl/ip/mmu/dtlb.sv                 
./rtl/ip/mmu/lookup.sv               
./rtl/ip/mmu/ptw.sv                  
./rtl/ip/mmu/replace_2_port.sv       
./rtl/ip/mmu/tlb_top.sv 
./rtl/ip/mmu/itlb.sv                             
./rtl/ip/mmu/replace_1_port_dtlb.sv
./rtl/ip/mmu/mmu_debug_events.sv
./rtl/ip/mmu/mmu_core.sv 
./rtl/ip/multi_byte_i2c/i2c_master.sv
./rtl/ip/multi_byte_i2c/i2c_register.sv
./rtl/ip/multi_byte_i2c/i2c_wrapper.sv
./rtl/ip/SPI/spi_master.sv
./rtl/ip/SPI/spi_regs.sv
./rtl/ip/SPI/spi_wrapper.sv
./rtl/ip/UART/baud_gen.sv       
./rtl/ip/UART/ndff_sync1.sv     
./rtl/ip/UART/regs.sv           
./rtl/ip/UART/rx_top.sv         
./rtl/ip/UART/tx_async_fifo.sv  
./rtl/ip/UART/demux.sv          
./rtl/ip/UART/ndff_sync.sv      
./rtl/ip/UART/rx_async_fifo.sv  
./rtl/ip/UART/thr.sv            
./rtl/ip/UART/tx_top.sv         
./rtl/ip/UART/mux.sv            
./rtl/ip/UART/rbr.sv            
./rtl/ip/UART/rx_fsm.sv         
./rtl/ip/UART/tsr_controler.sv  
./rtl/ip/UART/uart_top.sv
./rtl/ip/axi2apb_bridge/apb_master.sv        
./rtl/ip/axi2apb_bridge/async_fifo_read.sv   
./rtl/ip/axi2apb_bridge/axi_slave.sv         
./rtl/ip/axi2apb_bridge/bridge_ndff_sync.sv         
./rtl/ip/axi2apb_bridge/arbiter.sv           
./rtl/ip/axi2apb_bridge/async_fifo_write.sv  
./rtl/ip/axi2apb_bridge/top_bridge.sv
./rtl/ip/clk_rst_cntrlr/apb_reg_clk_rst_ctrl.sv  
./rtl/ip/clk_rst_cntrlr/clk_mux_2to1.sv                 
./rtl/ip/clk_rst_cntrlr/system_clk_rst_gen.sv    
./rtl/ip/clk_rst_cntrlr/clk_int_div.sv           
./rtl/ip/clk_rst_cntrlr/rstgen_bypass.sv         
./rtl/ip/clk_rst_cntrlr/sync.sv                  
./rtl/ip/clk_rst_cntrlr/tc_clk_gating.sv  
./rtl/ip/clk_rst_cntrlr/tc_clk_or2.sv  
./rtl/ip/clk_rst_cntrlr/tc_clk_xor2.sv
./rtl/ip/clk_rst_cntrlr/clk_mux_2to1_test.sv  
./rtl/ip/clk_rst_cntrlr/system_rst_gen.sv      
./rtl/ip/clk_rst_cntrlr/tc_clk_mux2.sv
./rtl/ip/clk_rst_cntrlr/top_clk_rst_ctrl.sv 
./rtl/ip/clk_and_rst_bypass/BOOT_CONTROLLER.sv     
./rtl/ip/clk_and_rst_bypass/BOOT_PULSE_GEN_P.sv          
./rtl/ip/clk_and_rst_bypass/BOOT_CONTROLLER_TOP.sv    
./rtl/ip/clk_and_rst_bypass/PULSE_RST_GEN.sv
./rtl/ip/clk_and_rst_bypass/PINAKA_CLK_RST_BYPASS_TOP.sv  
./rtl/common/wd_timer/watchdog_sync.sv
./rtl/common/wd_timer/watchdog_timer.sv
./rtl/common/gpio_regfile/gpio_regfile.sv        
./rtl/common/gpio_regfile/pinmux_gpio_ss.sv
./rtl/common/gpio_regfile/gpio_top_regfile.sv
./rtl/common/top_register/top_async_fifo.sv
./rtl/common/top_register/top_cdc_ndff.sv
./rtl/common/top_register/top_cdc_pulse_sync.sv
./rtl/common/top_register/top_register.sv
./rtl/common/top_register/top_register_cdc.sv
./rtl/common/analog_register.sv
./rtl/common/analog_preboot.sv
./rtl/ip/trace_ip/async_fifo.sv
./rtl/ip/trace_ip/event_compare.sv    
./rtl/ip/trace_ip/read_pointer.sv  
./rtl/ip/trace_ip/trace_system_top.sv
./rtl/ip/trace_ip/write_pointer.sv    
./rtl/ip/trace_ip/capture_controller.sv 
./rtl/ip/trace_ip/event_mux.sv   
./rtl/ip/trace_ip/trace_cdc.sv
./rtl/ip/trace_ip/trace_top.sv    
./rtl/ip/trace_ip/circular_buffer.sv  
./rtl/ip/trace_ip/gpio_output.sv  
./rtl/ip/trace_ip/trace_register.sv  
./rtl/ip/trace_ip/trace_wrapper.sv
./rtl/ip/TRACE_UNIT/async_fifo_trace.sv   
./rtl/ip/TRACE_UNIT/apb_slave_reg_core_trace.sv  
./rtl/ip/TRACE_UNIT/atb_transmitter.sv                 
./rtl/ip/TRACE_UNIT/top_trace.sv
./rtl/ip/TRACE_UNIT/top_core_trace.sv
./rtl/top/pinaka.sv


}


